# Generated by Django 5.2.7 on 2025-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
