# Generated by Django 5.2.7 on 2025-10-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
